// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/Compogo/compogo/logger/level.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_Panic Level = 0
	Level_Error Level = 1
	Level_Warn  Level = 2
	Level_Info  Level = 3
	Level_Debug Level = 4
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "Panic",
		1: "Error",
		2: "Warn",
		3: "Info",
		4: "Debug",
	}
	Level_value = map[string]int32{
		"Panic": 0,
		"Error": 1,
		"Warn":  2,
		"Info":  3,
		"Debug": 4,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Compogo_compogo_logger_level_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_github_com_Compogo_compogo_logger_level_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Compogo_compogo_logger_level_proto_rawDescGZIP(), []int{0}
}

var File_github_com_Compogo_compogo_logger_level_proto protoreflect.FileDescriptor

const file_github_com_Compogo_compogo_logger_level_proto_rawDesc = "" +
	"\n" +
	"-github.com/Compogo/compogo/logger/level.proto\x12\x0ecompogo.logger*<\n" +
	"\x05Level\x12\t\n" +
	"\x05Panic\x10\x00\x12\t\n" +
	"\x05Error\x10\x01\x12\b\n" +
	"\x04Warn\x10\x02\x12\b\n" +
	"\x04Info\x10\x03\x12\t\n" +
	"\x05Debug\x10\x04B,Z*github.com/Compogo/compogo/protobuf/loggerb\x06proto3"

var (
	file_github_com_Compogo_compogo_logger_level_proto_rawDescOnce sync.Once
	file_github_com_Compogo_compogo_logger_level_proto_rawDescData []byte
)

func file_github_com_Compogo_compogo_logger_level_proto_rawDescGZIP() []byte {
	file_github_com_Compogo_compogo_logger_level_proto_rawDescOnce.Do(func() {
		file_github_com_Compogo_compogo_logger_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Compogo_compogo_logger_level_proto_rawDesc), len(file_github_com_Compogo_compogo_logger_level_proto_rawDesc)))
	})
	return file_github_com_Compogo_compogo_logger_level_proto_rawDescData
}

var file_github_com_Compogo_compogo_logger_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Compogo_compogo_logger_level_proto_goTypes = []any{
	(Level)(0), // 0: compogo.logger.Level
}
var file_github_com_Compogo_compogo_logger_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_Compogo_compogo_logger_level_proto_init() }
func file_github_com_Compogo_compogo_logger_level_proto_init() {
	if File_github_com_Compogo_compogo_logger_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Compogo_compogo_logger_level_proto_rawDesc), len(file_github_com_Compogo_compogo_logger_level_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Compogo_compogo_logger_level_proto_goTypes,
		DependencyIndexes: file_github_com_Compogo_compogo_logger_level_proto_depIdxs,
		EnumInfos:         file_github_com_Compogo_compogo_logger_level_proto_enumTypes,
	}.Build()
	File_github_com_Compogo_compogo_logger_level_proto = out.File
	file_github_com_Compogo_compogo_logger_level_proto_goTypes = nil
	file_github_com_Compogo_compogo_logger_level_proto_depIdxs = nil
}
