// Code generated by "stringer -type=Level"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Panic-0]
	_ = x[Fatal-1]
	_ = x[Error-2]
	_ = x[Warn-3]
	_ = x[Info-4]
	_ = x[Debug-5]
}

const _Level_name = "PanicFatalErrorWarnInfoDebug"

var _Level_index = [...]uint8{0, 5, 10, 15, 19, 23, 28}

func (i Level) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}
