// Code generated by "stringer -type=Step"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-0]
	_ = x[PreRun-1]
	_ = x[Run-2]
	_ = x[PostRun-3]
	_ = x[PreWait-4]
	_ = x[Wait-5]
	_ = x[PostWait-6]
	_ = x[PreStop-7]
	_ = x[Stop-8]
	_ = x[PostStop-9]
}

const _Step_name = "InitPreRunRunPostRunPreWaitWaitPostWaitPreStopStopPostStop"

var _Step_index = [...]uint8{0, 4, 10, 13, 20, 27, 31, 39, 46, 50, 58}

func (i Step) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Step_index)-1 {
		return "Step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Step_name[_Step_index[idx]:_Step_index[idx+1]]
}
