// Code generated by "stringer -type=Step"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-0]
	_ = x[BindFlag-1]
	_ = x[Configuration-2]
	_ = x[PreExecute-3]
	_ = x[Execute-4]
	_ = x[PostExecute-5]
	_ = x[PreWait-6]
	_ = x[Wait-7]
	_ = x[PostWait-8]
	_ = x[PreStop-9]
	_ = x[Stop-10]
	_ = x[PostStop-11]
}

const _Step_name = "InitBindFlagConfigurationPreExecuteExecutePostExecutePreWaitWaitPostWaitPreStopStopPostStop"

var _Step_index = [...]uint8{0, 4, 12, 25, 35, 42, 53, 60, 64, 72, 79, 83, 91}

func (i Step) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Step_index)-1 {
		return "Step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Step_name[_Step_index[idx]:_Step_index[idx+1]]
}
