// Code generated by "stringer -type=Step"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreRun-0]
	_ = x[Run-1]
	_ = x[PostRun-2]
	_ = x[PreWait-3]
	_ = x[Wait-4]
	_ = x[PostWait-5]
	_ = x[PreStop-6]
	_ = x[Stop-7]
	_ = x[PostStop-8]
}

const _Step_name = "PreRunRunPostRunPreWaitWaitPostWaitPreStopStopPostStop"

var _Step_index = [...]uint8{0, 6, 9, 16, 23, 27, 35, 42, 46, 54}

func (i Step) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Step_index)-1 {
		return "Step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Step_name[_Step_index[idx]:_Step_index[idx+1]]
}
